# Generated by Django 5.2.3 on 2025-06-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_task_originating_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Projetos arquivados são somente leitura e não aparecem nas listas principais.', verbose_name='Arquivado'),
        ),
    ]
