# Generated by Django 5.2.3 on 2025-06-25 03:37

import backend.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectmember_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=backend.projects.models.get_attachment_upload_path),
        ),
    ]
